apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenminhquanzp01/3-tier-app.git
    targetRevision: main
    path: my-app       # Thư mục chứa Chart.yaml trong repo ứng dụng
    helm:
      valueFiles:
        - values.yaml  # file bạn sẽ update image tag
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
