apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-3-tier
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenminhquanzp01/3-tier-app.git
    targetRevision: main
    path: my-app
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true